### ISSUE TITLE
Align auth section Vault API with the Unified APIs

### ISSUE THREAD

**Issue by Gdewilde** [apideck-libraries/openapi-specs#4]
<img width="902" alt="Screenshot 2021-03-01 at 19 42 30" src="https://user-images.githubusercontent.com/1112129/109543295-64e87000-7ac6-11eb-86b9-7b0921f3f64f.png">

Should be:
<img width="910" alt="Screenshot 2021-03-01 at 19 42 23" src="https://user-images.githubusercontent.com/1112129/109543371-72055f00-7ac6-11eb-94dc-23ae76ecfeb7.png">

**Comment by elsmr** [comment]
Fixed in f25122a3fcfd3dd45925c30876a17195956c2d7b
