### ISSUE TITLE
Link integration settings guide

### ISSUE THREAD

**Issue by Gdewilde** [apideck-libraries/openapi-specs#5]
Spec: Vault API

Link to sample: https://github.com/apideck-samples/integration-settings
Remove coming soon label

<img width="916" alt="Screenshot 2021-03-01 at 20 06 52" src="https://user-images.githubusercontent.com/1112129/109546575-b09d1880-7aca-11eb-91a0-dd073cb35de5.png">

**Comment by elsmr** [comment]
Fixed in f25122a3fcfd3dd45925c30876a17195956c2d7b
