### ISSUE TITLE
Request header field x-apideck-downstream-url is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by AliKhalili** [apideck-libraries/openapi-specs#8]
When I called the proxy endpoint in the browser, first the browser send a preflight request to the apideck server. In the response of that preflight request, the `Access-Control-Allow-Headers` header tells us which header names are valid. This is the value of that header: `content-type,x-amz-date,authorization,x-api-key,x-amz-security-token,x-amz-user-agent,x-apideck-app-id,x-apideck-consumer-id,x-apideck-service-id,x-apideck-auth-type,x-apideck-metadata,access-control-allow-origin,access-control-allow-credentials`
As you can see, there isn't `x-apideck-downstream-url` in the valid heders name, so when I called the proxy in the browser I faced with this error:
`Access to fetch at 'https://unify.apideck.com/proxy' from origin 'xxx' has been blocked by CORS policy: Request header field x-apideck-downstream-url is not allowed by Access-Control-Allow-Headers in preflight response.`
Could you please explain how can I solve this issue? Or there is a issue in the proxy implementation and you need to fix it first.
Thank you for your consideration.

**Comment by Gdewilde** [comment]
Hi Ali, Unify and Proxy can't be used client-side since you leak your API keys. Those calls need to be performed server-side.
