### ISSUE TITLE
Fix documentation for Vault authorize endpoint

### ISSUE THREAD

**Issue by AliKhalili** [apideck-libraries/openapi-specs#9]
I guess it should be 301 instead of 302 in the documentation:
https://github.com/apideck-libraries/openapi-specs/blob/b2d6b9981ded08b996a7ec69e986b3c39d26c739/vault.yml#L2506

**Comment by AliKhalili** [comment]
I think it would be more standard compatible if it returns 302.
[RFC 6749](https://datatracker.ietf.org/doc/html/rfc6749#section-1.7)

**Comment by Gdewilde** [comment]
@elsmr @nicklloyd any thoughts?

**Comment by Gdewilde** [comment]
Thanks for the feedback @AliKhalili! The team will have a look.

**Comment by elsmr** [comment]
Hi @AliKhalili, the OAuth spec you linked says

> While the examples in this specification show the use of the HTTP 302 status code, any other method available via the user-agent to accomplish this redirection is allowed and is considered to be an implementation detail.

So I would think 301 is fine? I'm just a bit hesitant making this change, as it's possible our users are relying on the current status code.

**Comment by elsmr** [comment]
Ah but our description is indeed saying 302, while our implementation is 301. I will fix that :smile: thanks for reporting 👍
